In [1]:
# Ejercicio 1: Creación y Atributos
import numpy as np

edades = np.array([22, 25, 30, 35, 40])

print("Dimensiones:", edades.ndim)
print("Forma:", edades.shape)
print("Tipo de dato:", edades.dtype)

edades_float = edades.astype(np.float64)
print("Array en float64:", edades_float)

Dimensiones: 1
Forma: (5,)
Tipo de dato: int64
Array en float64: [22. 25. 30. 35. 40.]


In [2]:
# Ejercicio 2: Secuencias Automáticas
ids_clientes = np.arange(1, 101)
puntos_grafico = np.linspace(0, 10, 50)

print("IDs clientes:", ids_clientes)
print("Puntos gráfico:", puntos_grafico)

IDs clientes: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Puntos gráfico: [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.

In [3]:
# Ejercicio 3: Matrices y Datos Aleatorios
matriz_aleatoria = np.random.rand(3, 4)
matriz_unos = np.ones((3, 4))

print("Matriz aleatoria 3x4:")
print(matriz_aleatoria)
print("\nMatriz de unos 3x4:")
print(matriz_unos)

Matriz aleatoria 3x4:
[[0.98787966 0.33363452 0.02931365 0.87811986]
 [0.13127367 0.33887125 0.04857413 0.98091675]
 [0.14919699 0.00226425 0.4475943  0.05988426]]

Matriz de unos 3x4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# Ejercicio 4: El Simulador de Inventario
sucursales = int(input("Ingrese la cantidad de Sucursales: "))
productos = int(input("Ingrese la cantidad de Productos: "))

inventario = np.zeros((sucursales, productos))

print("Base de datos de inventario inicializada correctamente")
print(inventario)

Base de datos de inventario inicializada correctamente
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
# Ejercicio 5: Redimensionando la realidad (Reshape)
vector = np.arange(1, 13)
matriz = vector.reshape(3, 4)

print("Matriz 3x4:")
print(matriz)
print("Dimensiones:", matriz.ndim)

Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimensiones: 2


In [7]:
# Ejercicio 6: El peso de los datos (Optimización)
temperaturas = np.array([25.5, 28.1, 22.4, 19.9, 30.2])
print("Tipo original:", temperaturas.dtype)

temperaturas_int = temperaturas.astype(np.int32)
print("Array convertido a int32:", temperaturas_int)

Tipo original: float64
Array convertido a int32: [25 28 22 19 30]


In [12]:
# Ejercicio 7: Simulador de Dados
tiradas = np.random.randint(1, 7, 10)
print("10 tiradas de dado:", tiradas)

10 tiradas de dado: [5 2 2 2 4 4 6 4 2 4]


In [17]:
# Ejercicio 8: Limpieza de sensores
humedad_texto = np.array(["45.2", "48.1", "42.5", "50.0"])
print("Array como texto:", humedad_texto)
print("Tipo de dato:", humedad_texto.dtype)

try:
    np.sum(humedad_texto)
except TypeError:
    print("Error: el array tiene dtype <U4 (texto Unicode). NumPy no puede realizar operaciones aritméticas sobre strings. Es necesario convertirlo a float64 con .astype() antes de operar.")

humedad_float = humedad_texto.astype(np.float64)
print("Array limpio float64:", humedad_float)

Array como texto: ['45.2' '48.1' '42.5' '50.0']
Tipo de dato: <U4
Error: el array tiene dtype <U4 (texto Unicode). NumPy no puede realizar operaciones aritméticas sobre strings. Es necesario convertirlo a float64 con .astype() antes de operar.
Array limpio float64: [45.2 48.1 42.5 50. ]


In [14]:
# Ejercicio 9: La Matriz Identidad
identidad = np.eye(4)
print("Matriz identidad 4x4:")
print(identidad)

print("\nMatriz identidad x 5:")
print(identidad * 5)

Matriz identidad 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriz identidad x 5:
[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]
