In [1]:
# Ejercicio 1: Slicing y Sub-matrices
import numpy as np

matriz = np.arange(1, 26).reshape(5, 5)
print("Matriz 5x5:")
print(matriz)

submatriz_central = matriz[1:4, 1:4]
print("\nSub-matriz central 3x3:")
print(submatriz_central)

ultima_columna = matriz[:, -1]
print("\nÚltima columna:")
print(ultima_columna)

Matriz 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sub-matriz central 3x3:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Última columna:
[ 5 10 15 20 25]


In [2]:
# Ejercicio 2: Estadísticas con Ejes (Axis)
ventas = np.array([
    [1500, 2000, 1800, 2200],
    [1100, 1300, 1200, 1500],
    [3000, 3100, 2900, 3500]
])

print("Venta total de toda la empresa:", np.sum(ventas))
print("Promedio de ventas por semana (axis=0):", np.mean(ventas, axis=0))
print("Venta máxima por sucursal (axis=1):", np.max(ventas, axis=1))

Venta total de toda la empresa: 25100
Promedio de ventas por semana (axis=0): [1866.66666667 2133.33333333 1966.66666667 2400.        ]
Venta máxima por sucursal (axis=1): [2200 1500 3500]


In [3]:
# Ejercicio 3: El poder de la Máscara Booleana
numeros = np.arange(1, 21)

mascara_pares = numeros % 2 == 0

pares = numeros[mascara_pares]
print("Números pares:", pares)

Números pares: [ 2  4  6  8 10 12 14 16 18 20]


In [4]:
# Ejercicio 4: Condiciones Múltiples (El Analista de RRHH)
edades = np.array([22, 55, 34, 19, 45, 61, 28, 30, 42])

entre_30_y_50 = edades[(edades >= 30) & (edades <= 50)]
print("Empleados entre 30 y 50 años:", entre_30_y_50)

extremos = edades[(edades < 25) | (edades > 55)]
print("Empleados menores de 25 o mayores de 55:", extremos)

Empleados entre 30 y 50 años: [34 45 30 42]
Empleados menores de 25 o mayores de 55: [22 19 61]


In [5]:
# Ejercicio 5: Modificación Condicional
sensor = np.zeros((4, 4))

sensor[1:3, 1:3] = 9

print("Matriz sensor con bloque central calentado:")
print(sensor)

Matriz sensor con bloque central calentado:
[[0. 0. 0. 0.]
 [0. 9. 9. 0.]
 [0. 9. 9. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Ejercicio 6: Desafío Integrador - El Profesor Robot
calificaciones = np.random.randint(1, 11, 50)
print("Calificaciones generadas:", calificaciones)

promedio = np.mean(calificaciones)
print(f"\nPromedio general del curso: {promedio:.2f}")

desaprobados = calificaciones[calificaciones < 4]
print(f"Cantidad de alumnos desaprobados: {desaprobados.size}")

calificaciones[calificaciones < 4] = 4

print("\nCalificaciones finales (sin aplazos):")
print(calificaciones)

Calificaciones generadas: [10  7  7  1  2  8  5  2  6  2  2 10  2  4  4  2  2  8  6  1  5  7  4  2
  1  3  3  4  4 10  2  5  4  6  8  2  4  1  7  1  7  3  3  5  3  6  7  2
  4  7]

Promedio general del curso: 4.42
Cantidad de alumnos desaprobados: 21

Calificaciones finales (sin aplazos):
[10  7  7  4  4  8  5  4  6  4  4 10  4  4  4  4  4  8  6  4  5  7  4  4
  4  4  4  4  4 10  4  5  4  6  8  4  4  4  7  4  7  4  4  5  4  6  7  4
  4  7]
